name: infra

on:
  push:
    branches:
      - master
      - main

jobs:
  validate:
    name: Validate Cloudformation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CF_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CF_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-2'
      - run: |
          aws cloudformation validate-template --template-body file://deployment/infra/templates/_master.template
  deploy:
    name: Create or Update Cloudformation Stack
    needs: [validate]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CF_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CF_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-2'
      - name: Deploy Cloudformation
        run: |
          aws cloudformation deploy --template-file deployment/infra/templates/serverless.template --stack-name CD-Notifications-Infra --parameter-overrides TopicName=CD-Notification SubscriptionEmail={{ secrets.SUBEMAIL }}